//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Mazitova_Arina.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Statistic = new HashSet<Statistic>();
            this.TourTable = new HashSet<TourTable>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_Team { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistic> Statistic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourTable> TourTable { get; set; }
    }
}
