//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Mazitova_Arina.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Match = new HashSet<Match>();
            this.Registration = new HashSet<Registration>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_Game { get; set; }
        public Nullable<int> ID_Format { get; set; }
        public Nullable<int> Players_Count { get; set; }
        public Nullable<int> Prize { get; set; }
        public Nullable<int> Minimum_rank { get; set; }
        public string Forbidden_things { get; set; }
        public Nullable<int> ID_Organizarion { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public string Regional_restrictions { get; set; }
        public string Status_Tour { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Format Format { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Match { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registration { get; set; }
    }
}
